var presetShapes = {
  // These shapes are automatically added to this file based on the contents of this directory. See Gruntfile.js.
  arc: require('./arc'),
  arrow: require('./arrow'),
  brace: require('./brace'),
  complex: require('./complex'),
  ellipse: require('./ellipse'),
  ellipseDouble: require('./ellipseDouble'),
  endoplasmicReticulum: require('./endoplasmicReticulum'),
  golgiApparatus: require('./golgiApparatus'),
  hexagon: require('./hexagon'),
  lineCatmullRom: require('./lineCatmullRom'),
  lineCurved: require('./lineCurved'),
  lineElbow: require('./lineElbow'),
  lineSegmented: require('./lineSegmented'),
  lineStraight: require('./lineStraight'),
  mimBinding: require('./mimBinding'),
  mimBranchingLeft: require('./mimBranchingLeft'),
  mimBranchingRight: require('./mimBranchingRight'),
  mimCatalysis: require('./mimCatalysis'),
  mimCleavage: require('./mimCleavage'),
  mimConversion: require('./mimConversion'),
  mimCovalentBond: require('./mimCovalentBond'),
  mimDegradation: require('./mimDegradation'),
  mimGap: require('./mimGap'),
  mimInhibition: require('./mimInhibition'),
  mimModification: require('./mimModification'),
  mimNecessaryStimulation: require('./mimNecessaryStimulation'),
  mimStimulation: require('./mimStimulation'),
  mimTranscriptionTranslation: require('./mimTranscriptionTranslation'),
  mitochondria: require('./mitochondria'),
  pentagon: require('./pentagon'),
  rectangle: require('./rectangle'),
  roundedRectangle: require('./roundedRectangle'),
  roundedRectangleDouble: require('./roundedRectangleDouble'),
  sarcoplasmicReticulum: require('./sarcoplasmicReticulum'),
  tBar: require('./tBar'),
  triangle: require('./triangle'),
};

module.exports = presetShapes;
